// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AllocationPriorityType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Counter")]
        #pragma warning disable CS1591
        Counter,
        #pragma warning restore CS1591
        [EnumMember(Value = "List")]
        #pragma warning disable CS1591
        List,
        #pragma warning restore CS1591
    }
}
