// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllocationMetaPatch : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The annotations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_annotations? Annotations { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_annotations Annotations { get; set; }
#endif
        /// <summary>The labels property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_labels? Labels { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_labels Labels { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch"/> and sets the default values.
        /// </summary>
        public AllocationMetaPatch()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "annotations", n => { Annotations = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_annotations>(global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_annotations.CreateFromDiscriminatorValue); } },
                { "labels", n => { Labels = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_labels>(global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_labels.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_annotations>("annotations", Annotations);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch_labels>("labels", Labels);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
