// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllocationAllocationRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>[Stage: Beta][FeatureFlag:CountsAndLists]Counters and Lists provide a set of actions to performon Counters and Lists during allocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_counters? Counters { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_counters Counters { get; set; }
#endif
        /// <summary>Ordered list of GameServer label selectors.If the first selector is not matched, the selection attempts the second selector, and so on.This is useful for things like smoke testing of new game servers.Note: This field can only be set if neither Required or Preferred is set.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>? GameServerSelectors { get; set; }
#nullable restore
#else
        public List<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector> GameServerSelectors { get; set; }
#endif
        /// <summary>The lists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_lists? Lists { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_lists Lists { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch? Metadata { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch Metadata { get; set; }
#endif
        /// <summary>The metaPatch property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch? MetaPatch { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch MetaPatch { get; set; }
#endif
        /// <summary>Specifies settings for multi-cluster allocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationMultiClusterSetting? MultiClusterSetting { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationMultiClusterSetting MultiClusterSetting { get; set; }
#endif
        /// <summary>The namespace property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Namespace { get; set; }
#nullable restore
#else
        public string Namespace { get; set; }
#endif
        /// <summary>Deprecated: Please use gameServerSelectors instead. This field is ignored if thegameServerSelectors field is setThe ordered list of preferred allocations out of the `required` set.If the first selector is not matched, the selection attempts the second selector, and so on.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>? PreferredGameServerSelectors { get; set; }
#nullable restore
#else
        public List<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector> PreferredGameServerSelectors { get; set; }
#endif
        /// <summary>[Stage: Beta][FeatureFlag:CountsAndLists]`Priorities` configuration alters the order in which `GameServers` are searched for matches to the configured `selectors`.Priority of sorting is in descending importance. I.e. The position 0 `priority` entry is checked first.For `Packed` strategy sorting, this priority list will be the tie-breaker within the least utilised infrastructure, to ensure optimalinfrastructure usage while also allowing some custom prioritisation of `GameServers`.For `Distributed` strategy sorting, the entire selection of `GameServers` will be sorted by this priority list to provide theorder that `GameServers` will be allocated by.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgonesAllocatorModule.Client.Models.AllocationPriority>? Priorities { get; set; }
#nullable restore
#else
        public List<global::AgonesAllocatorModule.Client.Models.AllocationPriority> Priorities { get; set; }
#endif
        /// <summary>GameServerSelector used for finding a GameServer with matching filters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector? RequiredGameServerSelector { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector RequiredGameServerSelector { get; set; }
#endif
        /// <summary>The scheduling property</summary>
        public global::AgonesAllocatorModule.Client.Models.AllocationRequestSchedulingStrategy? Scheduling { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest"/> and sets the default values.
        /// </summary>
        public AllocationAllocationRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            Scheduling = global::AgonesAllocatorModule.Client.Models.AllocationRequestSchedulingStrategy.Packed;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "counters", n => { Counters = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_counters>(global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_counters.CreateFromDiscriminatorValue); } },
                { "gameServerSelectors", n => { GameServerSelectors = n.GetCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>(global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lists", n => { Lists = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_lists>(global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_lists.CreateFromDiscriminatorValue); } },
                { "metaPatch", n => { MetaPatch = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch>(global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch>(global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch.CreateFromDiscriminatorValue); } },
                { "multiClusterSetting", n => { MultiClusterSetting = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMultiClusterSetting>(global::AgonesAllocatorModule.Client.Models.AllocationMultiClusterSetting.CreateFromDiscriminatorValue); } },
                { "namespace", n => { Namespace = n.GetStringValue(); } },
                { "preferredGameServerSelectors", n => { PreferredGameServerSelectors = n.GetCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>(global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector.CreateFromDiscriminatorValue)?.AsList(); } },
                { "priorities", n => { Priorities = n.GetCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationPriority>(global::AgonesAllocatorModule.Client.Models.AllocationPriority.CreateFromDiscriminatorValue)?.AsList(); } },
                { "requiredGameServerSelector", n => { RequiredGameServerSelector = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>(global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector.CreateFromDiscriminatorValue); } },
                { "scheduling", n => { Scheduling = n.GetEnumValue<global::AgonesAllocatorModule.Client.Models.AllocationRequestSchedulingStrategy>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_counters>("counters", Counters);
            writer.WriteCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>("gameServerSelectors", GameServerSelectors);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationRequest_lists>("lists", Lists);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch>("metadata", Metadata);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMetaPatch>("metaPatch", MetaPatch);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationMultiClusterSetting>("multiClusterSetting", MultiClusterSetting);
            writer.WriteStringValue("namespace", Namespace);
            writer.WriteCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>("preferredGameServerSelectors", PreferredGameServerSelectors);
            writer.WriteCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationPriority>("priorities", Priorities);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector>("requiredGameServerSelector", RequiredGameServerSelector);
            writer.WriteEnumValue<global::AgonesAllocatorModule.Client.Models.AllocationRequestSchedulingStrategy>("scheduling", Scheduling);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
