// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    /// <summary>
    /// LabelSelector used for finding a GameServer with matching labels.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AllocationLabelSelector : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Labels to match.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector_matchLabels? MatchLabels { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector_matchLabels MatchLabels { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector"/> and sets the default values.
        /// </summary>
        public AllocationLabelSelector()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "matchLabels", n => { MatchLabels = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector_matchLabels>(global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector_matchLabels.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationLabelSelector_matchLabels>("matchLabels", MatchLabels);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
