// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    /// <summary>
    /// GameServerSelector used for finding a GameServer with matching filters.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AllocationGameServerSelector : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The counters property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_counters? Counters { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_counters Counters { get; set; }
#endif
        /// <summary>The gameServerState property</summary>
        public global::AgonesAllocatorModule.Client.Models.GameServerSelectorGameServerState? GameServerState { get; set; }
        /// <summary>The lists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_lists? Lists { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_lists Lists { get; set; }
#endif
        /// <summary>Labels to match.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_matchLabels? MatchLabels { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_matchLabels MatchLabels { get; set; }
#endif
        /// <summary>PlayerSelector is filter for player capacity values.minAvailable should always be less or equal to maxAvailable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector? Players { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector Players { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector"/> and sets the default values.
        /// </summary>
        public AllocationGameServerSelector()
        {
            AdditionalData = new Dictionary<string, object>();
            GameServerState = global::AgonesAllocatorModule.Client.Models.GameServerSelectorGameServerState.READY;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "counters", n => { Counters = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_counters>(global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_counters.CreateFromDiscriminatorValue); } },
                { "gameServerState", n => { GameServerState = n.GetEnumValue<global::AgonesAllocatorModule.Client.Models.GameServerSelectorGameServerState>(); } },
                { "lists", n => { Lists = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_lists>(global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_lists.CreateFromDiscriminatorValue); } },
                { "matchLabels", n => { MatchLabels = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_matchLabels>(global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_matchLabels.CreateFromDiscriminatorValue); } },
                { "players", n => { Players = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector>(global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_counters>("counters", Counters);
            writer.WriteEnumValue<global::AgonesAllocatorModule.Client.Models.GameServerSelectorGameServerState>("gameServerState", GameServerState);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_lists>("lists", Lists);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationGameServerSelector_matchLabels>("matchLabels", MatchLabels);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector>("players", Players);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
