// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    /// <summary>
    /// Priority is a sorting option for GameServers with Counters or Lists based on the Capacity.Type: Sort by a &quot;Counter&quot; or a &quot;List&quot;.Key: The name of the Counter or List. If not found on the GameServer, has no impact.Order: Sort by &quot;Ascending&quot; or &quot;Descending&quot;. &quot;Descending&quot; a bigger Capacity is preferred.&quot;Ascending&quot; would be smaller Capacity is preferred.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AllocationPriority : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The key property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Key { get; set; }
#nullable restore
#else
        public string Key { get; set; }
#endif
        /// <summary>The order property</summary>
        public global::AgonesAllocatorModule.Client.Models.PriorityOrder? Order { get; set; }
        /// <summary>The type property</summary>
        public global::AgonesAllocatorModule.Client.Models.AllocationPriorityType? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationPriority"/> and sets the default values.
        /// </summary>
        public AllocationPriority()
        {
            AdditionalData = new Dictionary<string, object>();
            Order = global::AgonesAllocatorModule.Client.Models.PriorityOrder.Ascending;
            Type = global::AgonesAllocatorModule.Client.Models.AllocationPriorityType.Counter;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationPriority"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationPriority CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationPriority();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "key", n => { Key = n.GetStringValue(); } },
                { "order", n => { Order = n.GetEnumValue<global::AgonesAllocatorModule.Client.Models.PriorityOrder>(); } },
                { "type", n => { Type = n.GetEnumValue<global::AgonesAllocatorModule.Client.Models.AllocationPriorityType>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("key", Key);
            writer.WriteEnumValue<global::AgonesAllocatorModule.Client.Models.PriorityOrder>("order", Order);
            writer.WriteEnumValue<global::AgonesAllocatorModule.Client.Models.AllocationPriorityType>("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
