// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    /// <summary>
    /// PlayerSelector is filter for player capacity values.minAvailable should always be less or equal to maxAvailable.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AllocationPlayerSelector : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The maxAvailable property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaxAvailable { get; set; }
#nullable restore
#else
        public string MaxAvailable { get; set; }
#endif
        /// <summary>The minAvailable property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MinAvailable { get; set; }
#nullable restore
#else
        public string MinAvailable { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector"/> and sets the default values.
        /// </summary>
        public AllocationPlayerSelector()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationPlayerSelector();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "maxAvailable", n => { MaxAvailable = n.GetStringValue(); } },
                { "minAvailable", n => { MinAvailable = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("maxAvailable", MaxAvailable);
            writer.WriteStringValue("minAvailable", MinAvailable);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
