// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AllocationAllocationResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The address property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Address { get; set; }
#nullable restore
#else
        public string Address { get; set; }
#endif
        /// <summary>The addresses property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusAddress>? Addresses { get; set; }
#nullable restore
#else
        public List<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusAddress> Addresses { get; set; }
#endif
        /// <summary>(Beta, CountsAndLists feature flag) Status of Counters and Lists on allocation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_counters? Counters { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_counters Counters { get; set; }
#endif
        /// <summary>The gameServerName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GameServerName { get; set; }
#nullable restore
#else
        public string GameServerName { get; set; }
#endif
        /// <summary>The lists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_lists? Lists { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_lists Lists { get; set; }
#endif
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerMetadata? Metadata { get; set; }
#nullable restore
#else
        public global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerMetadata Metadata { get; set; }
#endif
        /// <summary>The nodeName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NodeName { get; set; }
#nullable restore
#else
        public string NodeName { get; set; }
#endif
        /// <summary>The ports property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusPort>? Ports { get; set; }
#nullable restore
#else
        public List<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusPort> Ports { get; set; }
#endif
        /// <summary>The source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Source { get; set; }
#nullable restore
#else
        public string Source { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse"/> and sets the default values.
        /// </summary>
        public AllocationAllocationResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "address", n => { Address = n.GetStringValue(); } },
                { "addresses", n => { Addresses = n.GetCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusAddress>(global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusAddress.CreateFromDiscriminatorValue)?.AsList(); } },
                { "counters", n => { Counters = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_counters>(global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_counters.CreateFromDiscriminatorValue); } },
                { "gameServerName", n => { GameServerName = n.GetStringValue(); } },
                { "lists", n => { Lists = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_lists>(global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_lists.CreateFromDiscriminatorValue); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerMetadata>(global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerMetadata.CreateFromDiscriminatorValue); } },
                { "nodeName", n => { NodeName = n.GetStringValue(); } },
                { "ports", n => { Ports = n.GetCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusPort>(global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusPort.CreateFromDiscriminatorValue)?.AsList(); } },
                { "source", n => { Source = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("address", Address);
            writer.WriteCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusAddress>("addresses", Addresses);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_counters>("counters", Counters);
            writer.WriteStringValue("gameServerName", GameServerName);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationAllocationResponse_lists>("lists", Lists);
            writer.WriteObjectValue<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerMetadata>("metadata", Metadata);
            writer.WriteStringValue("nodeName", NodeName);
            writer.WriteCollectionOfObjectValues<global::AgonesAllocatorModule.Client.Models.AllocationResponseGameServerStatusPort>("ports", Ports);
            writer.WriteStringValue("source", Source);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
