// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum AllocationRequestSchedulingStrategy
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "Packed")]
        #pragma warning disable CS1591
        Packed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Distributed")]
        #pragma warning disable CS1591
        Distributed,
        #pragma warning restore CS1591
    }
}
