// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace AgonesAllocatorModule.Client.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GameServerSelectorGameServerState
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "READY")]
        #pragma warning disable CS1591
        READY,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALLOCATED")]
        #pragma warning disable CS1591
        ALLOCATED,
        #pragma warning restore CS1591
    }
}
