on:
  push:
  release:

jobs:
  build:
    name: Build and Publish Module
    runs-on: ubuntu-latest
    strategy:
      matrix:
        module: ["GameLiftAllocator"]
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: "8.0.x"
      - name: Publish Module
        run: dotnet publish -c Release modules/${{ matrix.module }} -o publish
      - name: Bundle Module Archive
        run: zip -r ${{ matrix.module }}.ccm publish/*
      - name: Publish to GH Release
        if: github.event_name == 'release'
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.module }}.ccm
          tag: ${{ github.ref }}
          overwrite: true
